entropydata.client.host=https://api.entropy-data.com
entropydata.client.apikey=your-api-key

entropydata.client.mariadb.connection.host=localhost
entropydata.client.mariadb.connection.port=3306
entropydata.client.mariadb.connection.database=test_db
entropydata.client.mariadb.connection.username=root
entropydata.client.mariadb.connection.password=password

entropydata.client.mariadb.assets.connectorid=mariadb-assets
entropydata.client.mariadb.assets.enabled=true
entropydata.client.mariadb.assets.pollinterval=PT10M
